Updated list of dependencies for Reveal SDK
RevealBi/Documentation pull request #296
Opened 2023-03-14 20:34 UTC by federicoprovera

2023-03-14 21:09 UTC, brianlagunas commented
when you update the web md files to use headers instead of an additional column for the platform, be sure to copy/paste the information into the japanese docs too 
![image](https://user-images.githubusercontent.com/835562/225136779-e5d04218-a32c-4604-8132-63a76a13e2d4.png)

2023-03-14 21:09 UTC, brianlagunas requested changes

2023-03-14 21:09 UTC, brianlagunas commented on docs/web/third-party-software.md
> +|ASP .NET|[Newtonsoft.Json](https://www.newtonsoft.com/json)|[MIT](https://opensource.org/licenses/mit-license.html)|
why add a column for the platform when you can create a sub heading in markdown?

## ASP.NET
...

## Node.js
...

## Java
...

2023-03-15 15:00 UTC, brianlagunas requested changes

2023-03-15 15:00 UTC, brianlagunas commented on docs/web/third-party-software.md
> +**ASP .NET**
please use markdown heading with a double "#" for example: `## ASP.NET`

2023-03-15 15:19 UTC, federicoprovera commented on docs/web/third-party-software.md
> +**ASP .NET**
Done.

2023-03-15 16:29 UTC, brianlagunas approved these changes

2023-03-15 16:29 UTC, merged