Updates to WPF documentation
RevealBi/Documentation pull request #305
Opened 2023-05-02 20:13 UTC by luispandolfi

Updated WPF documentation to be similar in structure to the Web documentation.

2023-05-02 20:38 UTC, brianlagunas requested changes
Please make these same changes in the Japanese docs. `i18n/ja/docusaurus-plugin-content-docs/current/wpf`

Just copy and paste the Japanese text.

2023-05-02 22:22 UTC, luispandolfi commented
> Please make these same changes in the Japanese docs. `i18n/ja/docusaurus-plugin-content-docs/current/wpf`
> 
> Just copy and paste the Japanese text.

Did it

2023-05-02 22:50 UTC, brianlagunas commented on i18n/ja/docusaurus-plugin-content-docs/current.json
> +  },
How did you generate these? Did you run the command line or did you do it manually?

2023-05-03 15:41 UTC, brianlagunas commented on i18n/ja/docusaurus-plugin-content-docs/current.json
> +  },
Can you run the translation string command for English too? When you generate the translation strings, but you must generate for both English and Japanese.

2023-05-03 16:58 UTC, brianlagunas approved these changes

2023-05-03 16:58 UTC, merged