Updated release notes and known issues for v1.6.2
RevealBi/Documentation pull request #381
Opened 2024-01-04 18:23 UTC by TorreyBetts

2024-01-04 19:10 UTC, brianlagunas requested changes

2024-01-04 19:10 UTC, brianlagunas commented on docs/web/release-notes.md
> +### Enhancements
remove the "Enhancements" section and place it's content under "New Features"

2024-01-04 19:46 UTC, TorreyBetts commented on docs/web/release-notes.md
> +### Enhancements
Updated the notes

2024-01-05 14:56 UTC, brianlagunas requested changes
All that's left is to cop/paste this into the japanese release notes

2024-01-05 15:54 UTC, brianlagunas approved these changes

2024-01-05 15:54 UTC, merged