Update tutorials - Candlestick chart
RevealBi/Documentation pull request #463
Opened 2024-10-30 15:03 UTC by vulh-infragistics

2024-10-30 15:12 UTC, brianlagunas requested changes

2024-10-30 15:12 UTC, brianlagunas commented on docs/user/images/add-visualization-button.png
this image is difficult to see/read

2024-10-30 15:12 UTC, brianlagunas commented on docs/user/images/candlestick-chart-types.png
The candle stick chart type is not visible in the Chart Types dropdown. Maybe bring attention to it by placing a red rectangle around it in the drop down.

2024-10-31 06:59 UTC, vulh-infragistics commented on docs/user/images/add-visualization-button.png
I have replaced with bigger image

2024-10-31 07:00 UTC, vulh-infragistics commented on docs/user/images/candlestick-chart-types.png
Added

2024-10-31 14:29 UTC, brianlagunas approved these changes

2024-10-31 14:29 UTC, merged