User docs tutorials - kpi-gauge chart
RevealBi/Documentation pull request #475
Opened 2024-11-01 08:34 UTC by vulh-infragistics

2024-11-01 19:00 UTC, brianlagunas requested changes

2024-11-01 19:00 UTC, brianlagunas commented on docs/user/tutorials-kpi-gauge.md
We need to fix the table layout as the text is not aligned properly in the table cell

![image](https://github.com/user-attachments/assets/eaf2b30c-a39d-4446-96cb-92dce0c53dd4)

2024-11-01 19:15 UTC, brianlagunas commented on docs/user/tutorials-kpi-gauge.md
would putting it in a two-column table look better? Title in the first column, image in the second column?

2024-11-04 07:13 UTC, vulh-infragistics commented on docs/user/tutorials-kpi-gauge.md
I think you are viewing the pre-updated docs. I have updated the table to have a blank header and the links go to new lines.
I also updated to align the table cell content to be center:
![image](https://github.com/user-attachments/assets/3e9a5159-4c1a-4a15-b9a7-e14fe1b615ca)

2024-11-05 08:50 UTC, hainv-ohio commented on docs/user/tutorials-kpi-gauge.md
Should be fixed now. @vulh-infragistics @brianlagunas

2024-11-05 15:09 UTC, hainv-ohio requested changes

2024-11-05 15:09 UTC, hainv-ohio commented on docs/user/tutorials-kpi-gauge.md
>  |                                  |                                                                        |
@vulh-infragistics also fix the tables in here to remove the top empty headers

2024-11-06 07:47 UTC, vulh-infragistics commented on docs/user/tutorials-kpi-gauge.md
>  |                                  |                                                                        |
Hi @hainv-ohio 
This should be fixed with the changes in the commit https://github.com/RevealBi/Documentation/pull/488/commits/4f73395437eaa01a88833a6e974919d9652adfc7

This removed the border inside the table. And it looks like:
![image](https://github.com/user-attachments/assets/ae9bb303-0264-435c-9611-cc1c061b6a6a)

2024-11-06 09:11 UTC, merged