Update Visualization Types - Text View of user document
RevealBi/Documentation pull request #484
Opened 2024-11-04 03:09 UTC by recca5p

2024-11-04 09:34 UTC, hainv-ohio requested changes

2024-11-04 09:34 UTC, hainv-ohio commented on docs/user/visualization-types/images/text-view-conditional-formatting.png
9The new image is incorrect, it should show the ability to do conditional formatting like the old image.

2024-11-04 09:39 UTC, recca5p commented on docs/user/visualization-types/images/text-view-conditional-formatting.png
I have updated the new screenshot, please re-review it

2024-11-05 07:16 UTC, hainv-ohio requested changes

2024-11-05 07:16 UTC, hainv-ohio commented on docs/user/visualization-types/images/text-view-conditional-formatting.png
@recca5p revenue should be in currency format, not a simple number

2024-11-05 07:28 UTC, hainv-ohio requested changes

2024-11-05 07:28 UTC, hainv-ohio commented on docs/user/visualization-types/text-view.md
Remove ", as explained in [this section](text-view).". in line 16. It's pointing to itself.

2024-11-05 10:52 UTC, recca5p commented on docs/user/visualization-types/images/text-view-conditional-formatting.png
Updated, please re-review it

2024-11-05 10:52 UTC, recca5p commented on docs/user/visualization-types/text-view.md
Removed, please re-review it

2024-11-05 13:22 UTC, hainv-ohio approved these changes

2024-11-05 13:22 UTC, merged