Update Fields - Sort of user document
RevealBi/Documentation pull request #497
Opened 2024-11-04 08:46 UTC by recca5p

2024-11-05 10:12 UTC, hainv-ohio requested changes

2024-11-05 10:12 UTC, hainv-ohio commented on docs/user/fields/sort-by-field.md
>    - [Ordering String Dates in Chronological Order](#ordering-string-dates-in-chronological-order)
Remove, we don't need this

2024-11-05 10:12 UTC, hainv-ohio commented on docs/user/fields/sort-by-field.md
>  Once done, select **Update Field**. Your information will now be ordered
Add 2 new lines here.
![image](https://github.com/user-attachments/assets/ba1269cf-b40b-4836-b7ff-e5aa34a5b6c5)

2024-11-05 11:13 UTC, recca5p commented on docs/user/fields/sort-by-field.md
>    - [Ordering String Dates in Chronological Order](#ordering-string-dates-in-chronological-order)
Removed

2024-11-05 11:13 UTC, recca5p commented on docs/user/fields/sort-by-field.md
>  Once done, select **Update Field**. Your information will now be ordered
Added

2024-11-06 07:24 UTC, hainv-ohio approved these changes

2024-11-06 07:25 UTC, merged