Update Fields - Calculated Fields - Overview of user document
RevealBi/Documentation pull request #500
Opened 2024-11-04 09:26 UTC by recca5p

…erview

2024-11-04 10:29 UTC, hainv-ohio requested changes

2024-11-04 10:29 UTC, hainv-ohio commented on docs/user/fields/calculated/images/new-calculated-field-dialog.png
It's quite small to see the text. Please zoom in the input field, don't need to show the whole UI below it.

2024-11-04 10:29 UTC, hainv-ohio commented on docs/user/fields/calculated/images/post-calculated-field-new-calculated-field-dialog.png
same comment, pls zoom in

2024-11-05 00:35 UTC, recca5p commented on docs/user/fields/calculated/images/post-calculated-field-new-calculated-field-dialog.png
I updated it, please re-review it

2024-11-05 00:35 UTC, recca5p commented on docs/user/fields/calculated/images/new-calculated-field-dialog.png
I updated it, please re-review it

2024-11-05 05:16 UTC, hainv-ohio approved these changes

2024-11-05 05:16 UTC, merged