Update Fields - Calculated Fields - Lookup & Reference of user document
RevealBi/Documentation pull request #506
Opened 2024-11-05 01:06 UTC by recca5p

2024-11-05 10:54 UTC, hainv-ohio requested changes

2024-11-05 10:54 UTC, hainv-ohio commented on docs/user/fields/calculated/lookup-reference.md
> +The following is an extract of the [HR Dataset 2016](http://download.infragistics.com/reportplus/help/samples/HR%20Dataset_2016.xlsx) "Employees"
Use local file

2024-11-05 10:54 UTC, hainv-ohio commented on docs/user/fields/calculated/lookup-reference.md
> +All samples included in the table below were created with the **[HR Dataset 2016](http://download.infragistics.com/reportplus/help/samples/HR%20Dataset_2016.xlsx)
Use local file

2024-11-05 10:59 UTC, hainv-ohio requested changes
![image](https://github.com/user-attachments/assets/bd011567-9c0c-411f-a351-a9eaa4b8379e)
Add breaks

2024-11-05 11:00 UTC, hainv-ohio requested changes

2024-11-05 11:00 UTC, hainv-ohio commented on docs/user/fields/calculated/lookup-reference.md
> +All samples included in the table below were created with the **[HR Dataset 2016](http://download.infragistics.com/reportplus/help/samples/HR%20Dataset_2016.xlsx)
Formating is not being applied: 
![image](https://github.com/user-attachments/assets/e5e8a268-5b28-47d8-8514-c67e20304462)

2024-11-06 07:23 UTC, recca5p commented on docs/user/fields/calculated/lookup-reference.md
> +All samples included in the table below were created with the **[HR Dataset 2016](http://download.infragistics.com/reportplus/help/samples/HR%20Dataset_2016.xlsx)
Done

2024-11-06 07:23 UTC, recca5p commented on docs/user/fields/calculated/lookup-reference.md
> +All samples included in the table below were created with the **[HR Dataset 2016](http://download.infragistics.com/reportplus/help/samples/HR%20Dataset_2016.xlsx)
Done

2024-11-06 07:23 UTC, recca5p commented on docs/user/fields/calculated/lookup-reference.md
> +The following is an extract of the [HR Dataset 2016](http://download.infragistics.com/reportplus/help/samples/HR%20Dataset_2016.xlsx) "Employees"
Done

2024-11-06 07:33 UTC, hainv-ohio approved these changes

2024-11-06 07:34 UTC, merged