Update Fields - Calculated Fields - Sample of user document
RevealBi/Documentation pull request #508
Opened 2024-11-05 01:25 UTC by recca5p

2024-11-05 13:48 UTC, hainv-ohio requested changes
The file links in tables, change them to use local files instead

2024-11-05 13:48 UTC, hainv-ohio commented on docs/user/fields/calculated/samples.md
>    - [YoY Analysis: Comparing Revenue Figures for a 2-Year Period](#yoy-analysis-comparing-revenue-figures-for-a-2-year-period)
Remove

2024-11-05 15:17 UTC, recca5p commented on docs/user/fields/calculated/samples.md
>    - [YoY Analysis: Comparing Revenue Figures for a 2-Year Period](#yoy-analysis-comparing-revenue-figures-for-a-2-year-period)
Removed

2024-11-05 15:21 UTC, recca5p commented
I cherry-pick the HR Dataset from user-docs branch so you will see that file duplicate @hainv-ohio

2024-11-06 07:36 UTC, hainv-ohio approved these changes

2024-11-06 07:37 UTC, merged